src/Entity/Membership.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity]
#[ORM\Table(name: '`membership`')]
#[ORM\ChangeTrackingPolicy('DEFERRED_EXPLICIT')]
class Membership
{
    public const PRICE = 1000;

    #[ORM\Id]
    #[ORM\Column(type: 'uuid')]
    private readonly Uuid $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'memberships')]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'id', nullable: true)]
    private readonly ?User $user;

    #[ORM\ManyToOne(targetEntity: Companion::class, inversedBy: 'memberships')]
    #[ORM\JoinColumn(name: 'companion_id', referencedColumnName: 'id', nullable: true)]
    private readonly ?Companion $companion;

    #[ORM\ManyToOne(targetEntity: Payment::class, inversedBy: 'memberships')]
    #[ORM\JoinColumn(name: 'payment_id', referencedColumnName: 'id', nullable: true)]
    private readonly ?Payment $payment;

    #[ORM\Column(type: Types::INTEGER, options: [
        'comment' => 'The price of this membership',
    ])]
    private readonly int $price;

    #[ORM\Column]
    private readonly \DateTimeImmutable $startAt;

    #[ORM\Column]
    private readonly \DateTimeImmutable $endAt;

    #[ORM\Column]
    private readonly \DateTimeImmutable $createdAt;

    #[ORM\Column(nullable: true)]
    #[Gedmo\Timestampable(on: 'update')]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $canceledAt = null;

    private function __construct(
        ?Payment $payment = null,
        ?User $user = null,
        ?Companion $companion = null,
        ?\DateTimeImmutable $startAt = null,
    ) {
        if (null === $user && null === $companion) {
            throw new \LogicException('Membership must be attached to a user or a companion.');
        }

        if (null !== $payment && !$payment->isApproved()) {
            throw new \LogicException('Given payment must be approved.');
        }

        if (null === $startAt) {
            $startAt = self::getNewMembershipStartAt();
        }

        $endAt = $startAt->modify('+1 year -1 day');
        $endAt = $endAt->setTime(23, 59, 59);

        $this->id = Uuid::v7();
        $this->payment = $payment;
        $this->user = $user;
        $this->companion = $companion;
        $this->price = self::PRICE;
        $this->startAt = $startAt;
        $this->endAt = $endAt;
        $this->createdAt = new \DateTimeImmutable();
    }

    public static function createForUser(User $user, ?Payment $payment = null, ?\DateTimeImmutable $startAt = null): self
    {
        $membership = new self($payment, user: $user, startAt: $startAt);
        $user->addMembership($membership);

        return $membership;
    }

    public static function createForCompanion(Companion $companion, Payment $payment, ?\DateTimeImmutable $startAt = null): self
    {
        $membership = new self($payment, companion: $companion, startAt: $startAt);
        $companion->addMembership($membership);

        return $membership;
    }

    /**
     * Returns the next date which will be used when creating a new Membership.
     */
    public static function getNewMembershipStartAt(): \DateTimeImmutable
    {
        $startAt = new \DateTimeImmutable('first day of july');
        if ($startAt > new \DateTimeImmutable()) {
            $startAt = $startAt->modify('-1 year');
        }

        return $startAt;
    }

    public function isValid(): bool
    {
        return $this->isValidAt(new \DateTimeImmutable());
    }

    public function isCanceled(): bool
    {
        return null !== $this->canceledAt;
    }

    public function isValidAt(\DateTimeImmutable $date): bool
    {
        if ($this->isCanceled()) {
            return false;
        }

        return $this->startAt <= $date && $date <= $this->endAt;
    }

    public function isInFuture(): bool
    {
        return $this->startAt > new \DateTimeImmutable();
    }

    public function isPast(): bool
    {
        return $this->endAt < new \DateTimeImmutable();
    }

    public function cancel(): self
    {
        $this->canceledAt = new \DateTimeImmutable();

        return $this;
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function getCompanion(): ?Companion
    {
        return $this->companion;
    }

    public function getPerson(): User|Companion
    {
        /* @phpstan-ignore-next-line */
        return $this->user ?? $this->companion;
    }

    public function getPayment(): ?Payment
    {
        return $this->payment;
    }

    public function getPrice(): int
    {
        return $this->price;
    }

    public function getStartAt(): \DateTimeImmutable
    {
        return $this->startAt;
    }

    public function getEndAt(): \DateTimeImmutable
    {
        return $this->endAt->setTime(0, 0, 0);
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function getCanceledAt(): ?\DateTimeImmutable
    {
        return $this->canceledAt;
    }
}

src/Entity/PersonTrait.php
<?php

declare(strict_types=1);

namespace App\Entity;

trait PersonTrait
{
    public function isChild(?\DateTimeInterface $atDate = null): bool
    {
        return $this->getAge($atDate) < 13;
    }

    public function isAdult(?\DateTimeInterface $atDate = null): bool
    {
        return $this->getAge($atDate) >= 18;
    }

    public function getAge(?\DateTimeInterface $atDate = null): int
    {
        if (null === $atDate) {
            $atDate = new \DateTimeImmutable();
        }

        return $atDate->diff($this->birthDate)->y;
    }

    public function getFullName(): string
    {
        return $this->firstName.' '.$this->lastName;
    }

    public function getPublicName(): string
    {
        return $this->firstName.' '.mb_substr($this->lastName, 0, 1);
    }

    public function getDiet(): ?Diet
    {
        return $this->diet;
    }

    public function isLactoseIntolerant(): bool
    {
        return $this->lactoseIntolerant;
    }

    public function isGlutenIntolerant(): bool
    {
        return $this->glutenIntolerant;
    }

    public function getDietDetails(): ?string
    {
        return $this->dietDetails;
    }
}

src/Entity/Registration.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\RegistrationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: RegistrationRepository::class)]
#[ORM\Table(name: '`registration`')]
#[ORM\Index(name: 'idx_registration_status', fields: ['status'])]
#[ORM\ChangeTrackingPolicy('DEFERRED_EXPLICIT')]
class Registration
{
    /**
     * This property should be marked as readonly but is not due to a bug in Doctrine.
     *
     * @see https://github.com/doctrine/orm/issues/9863
     */
    #[ORM\Id]
    #[ORM\Column(type: 'uuid')]
    private Uuid $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'registrations')]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'id', nullable: false)]
    private readonly User $user;

    #[ORM\ManyToOne(targetEntity: Event::class, inversedBy: 'registrations')]
    #[ORM\JoinColumn(name: 'event_id', referencedColumnName: 'id', nullable: false)]
    private readonly Event $event;

    #[ORM\Column(type: 'string', length: 20, enumType: RegistrationStatus::class, options: [
        'comment' => 'Status of this registration (waiting_payment, confirmed, canceled)',
    ])]
    private RegistrationStatus $status = RegistrationStatus::WAITING_PAYMENT;

    #[ORM\Column(type: Types::INTEGER, options: [
        'comment' => 'The total price choose by the user.',
    ])]
    private int $price = 0;

    #[ORM\Column(type: Types::INTEGER, options: [
        'comment' => 'How many bikes are needed by participants?',
    ])]
    private int $neededBike = 0;

    /**
     * This date is computed at the registration booking date using the age of
     * people at the first stage of this booking (because price can be
     * different when using the date of the booking).
     */
    #[ORM\Column(type: Types::INTEGER, options: [
        'comment' => 'How many children are part of this trip?',
    ])]
    private int $nbChildren = 0;

    #[ORM\Column]
    private readonly \DateTimeImmutable $createdAt;

    #[ORM\Column(nullable: true)]
    #[Gedmo\Timestampable(on: 'update')]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(nullable: true, options: [
        'comment' => 'Date on which the reservation was confirmed.',
    ])]
    private ?\DateTimeImmutable $confirmedAt = null;

    #[ORM\Column(nullable: true, options: [
        'comment' => 'Date on which the reservation was canceled.',
    ])]
    private ?\DateTimeImmutable $canceledAt = null;

    /**
     * @var Collection<int, StageRegistration>
     */
    #[ORM\OneToMany(targetEntity: StageRegistration::class, mappedBy: 'registration', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $stagesRegistrations;

    /**
     * @var Collection<int, Payment>
     */
    #[ORM\OneToMany(targetEntity: Payment::class, mappedBy: 'registration')]
    #[ORM\OrderBy(['createdAt' => 'ASC'])]
    private Collection $payments;

    /**
     * @var Collection<int, Companion>
     */
    #[ORM\ManyToMany(targetEntity: Companion::class, inversedBy: 'registrations')]
    #[ORM\JoinTable(name: 'registrations_companions')]
    private Collection $companions;

    public function __construct(User $user, Event $event)
    {
        $this->id = Uuid::v7();
        $this->user = $user;
        $this->event = $event;
        $this->createdAt = new \DateTimeImmutable();
        $this->payments = new ArrayCollection();
        $this->companions = new ArrayCollection();

        if ($event->isAT()) {
            $this->stagesRegistrations = new ArrayCollection();
        } else {
            $stagesRegistrations = [];
            $stages = $event->getStages();
            $nbStages = \count($stages);
            for ($i = 0; $i < $nbStages; ++$i) {
                /** @var Stage $stage */
                $stage = $stages[$i];

                $stageRegistration = new StageRegistration($stage, $this);
                if (0 === $i) {
                    $stageRegistration->setPresentForBreakfast($event->firstDayIncludesBreakfast());
                    $stageRegistration->setPresentForLunch($event->firstDayIncludesLunch());
                } elseif ($i === $nbStages - 1) {
                    $stageRegistration->setPresentForLunch($event->lastDayIncludesLunch());
                    $stageRegistration->setPresentForDinner($event->lastDayIncludesDinner());
                }

                $stagesRegistrations[] = $stageRegistration;
            }

            $this->stagesRegistrations = new ArrayCollection($this->orderStagesRegistrations($stagesRegistrations));
        }
    }

    public function confirm(): void
    {
        if (RegistrationStatus::WAITING_PAYMENT !== $this->status) {
            throw new \LogicException("Cannot confirm a registration in {$this->status->value} status.");
        }

        $this->status = RegistrationStatus::CONFIRMED;
        $this->confirmedAt = new \DateTimeImmutable();
    }

    public function isConfirmed(): bool
    {
        return RegistrationStatus::CONFIRMED === $this->status;
    }

    public function isCanceled(): bool
    {
        return RegistrationStatus::CANCELED === $this->status;
    }

    public function canBeCanceled(): bool
    {
        if (RegistrationStatus::CONFIRMED !== $this->status) {
            return false;
        }

        return $this->getCancelationDate() > new \DateTimeImmutable();
    }

    public function getCancelationDate(): \DateTimeImmutable
    {
        if (null === $firstStage = $this->event->getFirstStage()) {
            throw new \RuntimeException('Registration linked to an event without stages!');
        }

        return $firstStage->getDate()->modify('-15 days');
    }

    public function cancel(): void
    {
        if ($this->isCanceled()) {
            throw new \LogicException("Cannot cancel registration {$this->getId()} (already canceled).");
        }

        $this->status = RegistrationStatus::CANCELED;
        $this->canceledAt = new \DateTimeImmutable();
    }

    public function isWaitingPayment(): bool
    {
        return RegistrationStatus::WAITING_PAYMENT === $this->status;
    }

    public function daysOfPresence(): int
    {
        return $this->stagesRegistrations->count();
    }

    public function payingDaysOfPresence(): float
    {
        $payingDaysOfPresence = $this->daysOfPresence() - $this->freeDaysOfPresence();

        if (null === $firstStageRegistration = $this->getStageRegistrationStart()) {
            throw new \LogicException('No stage registration found for given registration');
        }

        if (Meal::BREAKFAST !== $this->getFirstMeal()) {
            $payingDaysOfPresence -= $firstStageRegistration->includesMeal(Meal::LUNCH) ? .2 : .6;
        }

        if (null === $lastStageRegistration = $this->getStageRegistrationEnd()) {
            throw new \LogicException('No stage registration found for given registration');
        }

        if (Meal::DINNER !== $this->getLastMeal()) {
            $payingDaysOfPresence -= $lastStageRegistration->includesMeal(Meal::LUNCH) ? .4 : .8;
        }

        return (float) $payingDaysOfPresence;
    }

    public function freeDaysOfPresence(): int
    {
        return $this->getStagesRegistrations()->filter(static fn (StageRegistration $stageRegistration): bool => $stageRegistration->getStage()->isFree())->count();
    }

    public function getStageRegistrationStart(): ?StageRegistration
    {
        if (false !== $stageRegistration = $this->getStagesRegistrations()->first()) {
            return $stageRegistration;
        }

        return null;
    }

    public function getStageRegistrationEnd(): ?StageRegistration
    {
        if (false !== $stageRegistration = $this->getStagesRegistrations()->last()) {
            return $stageRegistration;
        }

        return null;
    }

    public function countPeople(): int
    {
        return $this->companions->count() + 1;
    }

    public function countChildren(): int
    {
        return $this->nbChildren;
    }

    public function computeChildren(): void
    {
        $this->nbChildren = \count($this->getChildren());
    }

    public function getStartAt(): ?\DateTimeImmutable
    {
        if (null === $stageRegistration = $this->getStageRegistrationStart()) {
            return null;
        }

        return $stageRegistration->getStage()->getDate();
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        if (null === $stageRegistration = $this->getStageRegistrationEnd()) {
            return null;
        }

        return $stageRegistration->getStage()->getDate();
    }

    public function isThisYear(): bool
    {
        return $this->getCreatedAt()->format('y') === date('y');
    }

    /**
     * If the first day is a free day, the first meal of the first paying day
     * must be the breakfast.
     */
    public function getFirstMeal(): Meal
    {
        if (null === $firstStageRegistration = $this->getStageRegistrationStart()) {
            throw new \LogicException('No stage registration found for given registration');
        }

        return $firstStageRegistration->getStage()->isFree() ? Meal::BREAKFAST : $firstStageRegistration->getFirstMeal();
    }

    /**
     * If the last day is a free day, the last meal of the last paying day must
     * be the dinner.
     */
    public function getLastMeal(): Meal
    {
        if (null === $lastStageRegistration = $this->getStageRegistrationEnd()) {
            throw new \LogicException('No stage registration found for given registration');
        }

        return $lastStageRegistration->getStage()->isFree() ? Meal::DINNER : $lastStageRegistration->getLastMeal();
    }

    /**
     * @return array<User|Companion>
     */

src/Controller/Profile/CompanionsController.php
<?php

declare(strict_types=1);

namespace App\Controller\Profile;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_USER')]
#[Route('/me/companions', name: 'profile_companions')]
class CompanionsController extends AbstractController
{
    public function __invoke(): Response
    {
        return $this->render('profile/companions.html.twig');
    }
}

src/Controller/Profile/HomepageController.php
<?php

declare(strict_types=1);

namespace App\Controller\Profile;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_USER')]
#[Route('/me', name: 'profile_homepage')]
class HomepageController extends AbstractController
{
    public function __invoke(Request $request): Response
    {
        return $this->render('profile/homepage.html.twig');
    }
}

templates/profile/companion_form.html.twig
{% extends '_base_profile.html.twig' %}

{% block title %}
    {% if creation %}
        Ajout d'un·e compagnon·e
    {% else %}
        {{ form.vars.data.fullName }}
    {% endif %}
{% endblock %}

{% block main %}
    {{ form_errors(form) }}

    {{ form_start(form) }}
    <fieldset class="form-group border p-3 mt-3">
        <legend class="w-auto px-2"><i class="fa-solid fa-id-card me-2"></i> Ses informations personnelles</legend>

        <div class="row">
            <div class="col-12 col-md-6">
                {{ form_row(form.firstName) }}
            </div>
            <div class="col-12 col-md-6">
                {{ form_row(form.lastName) }}
            </div>
        </div>
        {{ form_row(form.birthDate) }}
    </fieldset>

    <fieldset class="form-group border p-3 mt-3">
        <legend class="w-auto px-2"><i class="fa-solid fa-address-book me-2"></i> Ses coordonnées</legend>

        {{ form_row(form.email) }}
        {{ form_row(form.phoneNumber) }}
    </fieldset>

    <fieldset class="form-group border p-3 mt-3">
        <legend class="w-auto px-2"><i class="fa-solid fa-carrot me-2"></i> Son régime alimentaire</legend>

        {{ form_row(form.diet) }}

        <div class="row">
            <div class="col-12 col-md-6">
                {{ form_row(form.glutenIntolerant) }}
            </div>
            <div class="col-12 col-md-6">
                {{ form_row(form.lactoseIntolerant) }}
            </div>
        </div>

        {{ form_row(form.dietDetails) }}
    </fieldset>

    <div class="d-grid gap-2 mt-4">
        <button type="submit" class="btn btn-lg btn-primary">
            {% if creation %}Ajouter{% else %}Modifier{% endif %}
                </button>
    </div>

    {{ form_end(form) }}
{% endblock %}

templates/profile/companions.html.twig
{% extends '_base_profile.html.twig' %}

{% block title %}Tes compagnon·es{% endblock %}

{% block main %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for companion in app.user.companions %}
            <div class="col">
                <div class="card card-hover">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <h3 class="card-title fs-5">{{ companion.fullName }}</h3>
                                <p class="text-secondary mb-2">
                                    {{ companion.birthDate|format_date('short') }}<br />
                                    {{ companion.email }}
                                    {% if companion.phoneNumber is not null %}
                                        <span class="px-2">/</span>
                                    {% endif %}
                                    {% if companion.phoneNumber is not null %}
                                        {{ companion.phoneNumber|phone_number_format }}
                                    {% endif %}
                                </p>
                            </div>
                            <a href="{{ path('profile_companion_update', {id: companion.id}) }}" class="stretched-link">
                                <span class="d-none">Modifier {{ companion.fullName }}</span>
                                <i class="fa-solid fa-chevron-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="text-center"{% if app.environment == 'test' %} id="test-no-companion-text"{% endif %}>
                Tu n'as pas de compagnon·es pour le moment !
            </div>
        {% endfor %}
    </div>

    <div class="d-grid mt-4">
        <a href="{{ path('profile_companion_create') }}" class="btn btn-primary">
            Ajouter une·e compagnon·e
        </a>
    </div>
{% endblock %}

templates/profile/memberships.html.twig
{% extends '_base_profile.html.twig' %}

{% block title %}Tes adhésions à AlterCampagne{% endblock %}

{% block main %}
    {% if not app.user.isMember %}
        <div class="alert alert-danger">
            <b>Tu n'es actuellement pas membre de l'association.</b><br />
            Si tu veux participer à l'un de nos évènements ou à l'orga, une adhésion est obligatoire.<br />
            Pour en savoir plus : <twig:FAQQuestion slug="pourquoi-adherer-a-lassociation" class="btn btn-link p-0" />

            <div class="d-grid gap-2 mt-3">
                <twig:ButtonPost url="{{ path('payment_initiate_membership_payment') }}">
                    Adhérer à l'association
                </twig:ButtonPost>
            </div>
        </div>
    {% endif %}

    {% if app.user.memberships|length > 0 %}
        {% for membership in app.user.memberships %}
            <div class="card mb-2 {{ membership.isInFuture ? 'bg-warning-subtle' : membership.isValid ? 'bg-success-subtle' : 'bg-light-subtle' }}">
                <div class="card-body d-flex justify-content-between align-items-center{{ membership.isPast or membership.isCanceled ? ' text-secondary' }}">
                    Adhésion du {{ membership.startAt|format_date('long') }} au {{ membership.endAt|format_date('long') }}
                    {% if membership.isInFuture %}
                        <div class="badge bg-warning">Démarre bientôt</div>
                    {% elseif membership.isValid %}
                        <div class="badge bg-success">En cours</div>
                    {% elseif membership.isCanceled %}
                        <div class="badge bg-danger-subtle" data-bs-toggle="tooltip" title="Adhésion annulée le {{ membership.canceledAt|format_datetime('long', 'short') }}">
                            Annulée
                        </div>
                    {% else %}
                        <div class="badge bg-dark-subtle">Terminée</div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

        <div class="text-center">
            <small class="text-secondary">Les adhésions antérieures au 1er mai 2024 ne sont pas affichées ici.</small>
        </div>
    {% endif %}
{% endblock %}

templates/profile/registrations.html.twig
{% extends '_base_profile.html.twig' %}

{% block title %}Tes participations{% endblock %}

{% macro render_registration(registration, isComing) %}
    <div class="card mb-3">
        <div class="card-header d-flex justify-content-between align-items-center{% if registration.isCanceled %} bg-secondary-subtle{% elseif isComing %} bg-primary-subtle{% endif %}">
            <h3 class="card-title fs-4 m-0">{{ registration.event.name }}</h3>
            {% if registration.canceled %}
                <span class="badge bg-secondary">Inscription annulée</span>
            {% endif %}
        </div>
        <div class="card-body">
            <p class="card-text">
                <b>Arrivée</b> prévue le <b>{{ registration.stageRegistrationStart.stage.date|format_date('full') }}</b>
                pour le {{ registration.firstMeal|trans|lower }}
                .<br />
                <b>Départ</b> prévu le <b>{{ registration.stageRegistrationEnd.stage.date|format_date('full') }}</b>
                après le {{ registration.lastMeal|trans|lower }}
                .
            </p>
            {% if registration.neededBike > 0 %}
                <p class="card-text">
                    Avec <b>{{ registration.neededBike }} vélo{{ registration.neededBike > 1 ? 's' }} de prêt</b>.
                </p>
            {% endif %}
            {% if registration.companions|length > 0 %}
                <b>Tes compagnon·es :</b>
                <ul>
                    {% for companion in registration.companions %}
                        <li>{{ companion.fullname }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <p class="card-text">
                {% if registration.approvedPayment is not null %}
                    {% set payment = registration.approvedPayment %}
                    {% if payment.withInstalments %}
                        <b>Paiement</b> en {{ payment.instalments }} fois sans frais de <b>{{ payment.amount|format_price }}</b> initié le <b>{{ payment.approvedAt|format_date('short') }}</b>.
                    {% else %}
                        <b>Paiement</b> de <b>{{ payment.amount|format_price }}</b> réglé le <b>{{ payment.approvedAt|format_date('short') }}</b>.
                    {% endif %}
                    {% if payment.refunded %}
                        <br /><b>Remboursement</b> fait le <b>{{ payment.refundedAt|format_date('short') }}</b>.
                    {% endif %}
                {% else %}
                    <div class="alert alert-danger">
                        <b>Paiment non trouvé ! 😧</b><br />
                        Ce n'est pas normal, <a href="{{ path('contact') }}">contacte-nous pour en discuter !</a> 🙏
                    </div>
                {% endif %}
            </p>
            {% if isComing and not registration.isCanceled %}
                {% if registration.canBeCanceled %}
                    <div class="d-grid gap-2">
                        <twig:ButtonPostWithConfirmation
                            url="{{ path('registration_cancel', {id: registration.id}) }}"
                            buttonLabel="Annuler mon inscription"
                            btnClass="btn btn-outline-danger"
                            modalTitle="Annulation de ton inscription"
                            modalButtonClass="btn btn-danger"
                            modalButtonLabel="Confirmer l'annulation de mon inscription"
                        >
                            Cette action est <b>IRRÉVERSIBLE</b>.<br /><br />
                            {% if registration.approvedPayment.withInstalments %}
                                Tu seras remboursé de l'intégralité des paiements déjà effectués.
                            {% else %}
                                Tu seras remboursé de l'intégralité de ton paiement.
                            {% endif %}
                        </twig:ButtonPostWithConfirmation>
                        <small class="text-center text-secondary">
                            (disponible jusqu'au {{ registration.cancelationDate|format_date('long') }})
                        </small>
                    </div>
                {% else %}
                    <div class="alert bg-danger-subtle mb-0">
                        L'évènement démarre bientôt, ton inscription ne peut plus être annulée.
                        {% if registration.event.exchangeMarketLink is not null %}
                            <br />En revanche, peut-être que tu peux proposer tes places sur <a href="{{ registration.event.exchangeMarketLink }}" rel="nofollow">la bourse aux échanges</a> !
                        {% endif %}
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endmacro %}

{% block main %}
    <div class="justify-content-center">
            <h2 class="mb-3">À venir</h2>
            {% for registration in coming_registrations %}
                {{ _self.render_registration(registration, true) }}
            {% else %}
                Tu n'es inscrit à aucun évènement pour le moment !
            {% endfor %}

            {% if past_registrations|length > 0 %}
                <h2 class="mb-3 mt-4">Passées</h2>
                {% for registration in past_registrations %}
                    {{ _self.render_registration(registration, false) }}
                {% endfor %}
            {% endif %}
    </div>
{% endblock %}

templates/profile/update_contact_details.html.twig
{% extends '_base_profile.html.twig' %}

{% block title %}Mise à jour de tes coordonnées{% endblock %}

{% block main %}
    {{ form_errors(form) }}

    {{ form_start(form) }}
    <fieldset class="form-group border p-3 mt-3">
        <legend class="w-auto px-2"><i class="fa-solid fa-id-card me-2"></i> Tes informations personnelles</legend>

        <div class="row">
            <div class="col-12 col-md-6">
                {{ form_row(form.firstName) }}
            </div>
            <div class="col-12 col-md-6">
                {{ form_row(form.lastName) }}
            </div>
        </div>
        {{ form_row(form.publicName) }}
        {{ form_row(form.birthDate) }}
    </fieldset>

    <fieldset class="form-group border p-3 mt-3">
        <legend class="w-auto px-2"><i class="fa-solid fa-address-book me-2"></i> Tes coordonnées</legend>

        {{ form_row(form.email) }}
        {{ form_row(form.phoneNumber) }}
    </fieldset>

    <fieldset class="form-group border p-3 mt-3">
        <legend class="w-auto px-2"><i class="fa-solid fa-map-location-dot me-2"></i> Ton adresse postale</legend>

        {{ form_row(form.address.addressLine1) }}
        {{ form_row(form.address.addressLine2) }}

        <div class="row">
            <div class="col-12 col-md-4">
                {{ form_row(form.address.zipCode) }}
            </div>
            <div class="col-12 col-md-8">
                {{ form_row(form.address.city) }}
            </div>
        </div>

        {{ form_row(form.address.countryCode) }}
    </fieldset>

    <div class="d-grid gap-2 mt-4">
        <button type="submit" class="btn btn-lg btn-primary">Mettre à jour</button>
    </div>

    {{ form_end(form) }}
{% endblock %}